config/routes.rb
Rails.application.routes.draw do
  root 'templated_emails#index'

  resources :templated_emails

  resources :message_templates

  get '/about', to: 'static_pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message_template.rb
class MessageTemplate < ApplicationRecord
end

app/models/templated_email.rb
class TemplatedEmail < ApplicationRecord
  belongs_to :message_template

  validates :sender_name, presence: true
  validates :destination_email, presence: true
  validates_email_format_of :destination_email, :message => 'Not a valid email.'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/message_templates_controller.rb
class MessageTemplatesController < ApplicationController

  def show
    @message_template = MessageTemplate.find(params[:id])

    respond_to do |format|
      # display the template to a user.
      format.html

      # may be consumed by ajax
      format.json { render json: @message_template }
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
    render 'about'
  end
end

app/controllers/templated_emails_controller.rb
class TemplatedEmailsController < ApplicationController

  def index
    @templated_emails = TemplatedEmail.all
  end

  def new
    @templated_email = TemplatedEmail.new
  end

  def create
    @templated_email = TemplatedEmail.new(templated_email_parameters)

    if @templated_email.valid?
      TemplatedEmailMailer.with(templated_email: @templated_email).send_templated_email.deliver_now

      # persist the email now that it has been sent.
      @templated_email.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  private def templated_email_parameters
    params.require(:templated_email)
        .permit(:sender_name, :destination_email, :message_template_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_templates_helper.rb
module MessageTemplatesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/templated_emails_helper.rb
module TemplatedEmailsHelper

  # adds the bootstrap is-invalid class to the
  # supplied HTML class if the specified field
  # is invalid.
  def append_validity_css_class(existing_html_class, model, field_name)
    model.errors.messages[field_name].empty? ?
      existing_html_class :
      existing_html_class + " is-invalid"
  end

  def enumerate_field_errors(model, field_name)
    model.errors.messages[field_name]
        .map { |m| "<div class=\"invalid-feedback\">#{m}</div>" }
        .join
        .html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTemplatedEmails</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Email Sender</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "New email", new_templated_email_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "Sent Emails", templated_emails_path, class: "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/message_templates/show.erb
<div class="row">
  <h1>Message:</h1>
</div>

<div class="row">
  <div class="card">
    <h5 class="card-header"><%= @message_template.name %></h5>
    <div class="card-body">
      <p><%= @message_template.body.html_safe %></p>
    </div>
  </div>
</div>

app/views/static_pages/about.erb
<div class="row">
  <h1>About:</h1>
</div>
<div class="row">
  <p>This is an example application for sending templated emails. Click <%= link_to("to send a new email", new_templated_email_path) %>.</p>
</div>

app/views/templated_emails/index.erb
<div class="row">
  <h1>Previously Sent Emails:</h1>
</div>

<div class="row">

  <% if @templated_emails.empty? %>
    <p>There are no emails to display.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Sender</th>
          <th scope="col">Recipient</th>
          <th scope="col">Message</th>
          <th scope="col">Time and Date</th>
        </tr>
      </thead>
      <tbody>
        <% @templated_emails.each do |templated_email| %>
          <tr>
            <td><%= templated_email.sender_name %></td>
            <td><%= templated_email.destination_email %></td>
            <td><%= link_to templated_email.message_template.name, templated_email.message_template %></td>
            <td><%= templated_email.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/templated_emails/new.erb
<div class="row">
  <h1>Send a Templated Email</h1>
</div>

<%= form_for @templated_email do |f| %>
  <% if @templated_email.errors.any? %>
    <div class="alert alert-danger">Please correct the highlighted errors and try again.</div>
  <% end %>

  <div class="form-group">
    <%= f.label :sender_name %>
    <%= f.text_field :sender_name, class: append_validity_css_class('form-control', @templated_email, :sender_name) %>
    <%= enumerate_field_errors(@templated_email, :sender_name) %>
  </div>

  <div class="form-group">
    <%= f.label :destination_email %>
    <%= f.text_field :destination_email, class: append_validity_css_class('form-control', @templated_email, :destination_email) %>
    <%= enumerate_field_errors(@templated_email, :destination_email) %>
  </div>

  <div class="form-group">
    <%= f.label "Message Template" %>
    <%= f.select(:message_template_id,
                 options_from_collection_for_select(MessageTemplate.all, 'id', 'name', @templated_email.message_template_id),
                 {},
                 { :class => append_validity_css_class('form-control', @templated_email, :message_template) }) %>

    <%= enumerate_field_errors(@templated_email, :message_template) %>
  </div>

  <div class="form-group">
    <%= label_tag('message_preview_text_area', 'Message Preview') %>
    <div class="card">
      <div class="card-body" id="message_preview_text_area"></div>
    </div>
  </div>

  <p><%= f.submit "Send Email", class: "btn btn-primary" %></p>
<% end %>